# Generated by Django 4.2.13 on 2024-07-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTripInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('stay_details', models.CharField(max_length=255)),
                ('number_of_days', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('additional_preferences', models.CharField(max_length=255)),
            ],
        ),
    ]
