# Generated by Django 4.2.13 on 2024-07-08 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertripinfo',
            name='generated_plan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usertripinfo',
            name='trip_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
