# Generated by Django 4.2.13 on 2024-07-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0003_alter_usertripinfo_generated_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertripinfo',
            name='generated_plan',
            field=models.TextField(),
        ),
    ]
