# Generated by Django 4.2.13 on 2024-07-10 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0004_alter_usertripinfo_generated_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTripProgressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trip_id', models.CharField(max_length=255)),
                ('progress', models.TextField()),
            ],
        ),
    ]
