# Generated by Django 4.2.13 on 2024-07-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0005_usertripprogressinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertripprogressinfo',
            name='user_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
