# Generated by Django 4.2.13 on 2024-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0006_usertripprogressinfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertripprogressinfo',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
