# Generated by Django 4.2.13 on 2024-07-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0007_alter_usertripprogressinfo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertripprogressinfo',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
