# Generated by Django 4.2.13 on 2024-07-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0008_usertripprogressinfo_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertripprogressinfo',
            name='progress',
        ),
    ]
