# Generated by Django 4.2.13 on 2024-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0009_remove_usertripprogressinfo_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertripinfo',
            name='nearby_restaurants',
            field=models.TextField(default=''),
        ),
    ]
