# Generated by Django 4.2.13 on 2024-07-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0010_usertripinfo_nearby_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('trip_id', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('place', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('day', models.IntegerField()),
            ],
        ),
    ]
