# Generated by Django 4.2.13 on 2024-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0012_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertripinfo',
            name='nearby_bars',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usertripinfo',
            name='nearby_cafes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usertripinfo',
            name='nearby_night_clubs',
            field=models.TextField(default=''),
        ),
    ]
