# Generated by Django 4.2.13 on 2024-08-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0013_usertripinfo_nearby_bars_usertripinfo_nearby_cafes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertripinfo',
            name='nearby_bars',
        ),
        migrations.RemoveField(
            model_name='usertripinfo',
            name='nearby_cafes',
        ),
        migrations.RemoveField(
            model_name='usertripinfo',
            name='nearby_night_clubs',
        ),
    ]
