# Generated by Django 4.2.13 on 2024-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0014_remove_usertripinfo_nearby_bars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financelog',
            name='trip_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
