# Generated by Django 4.2.13 on 2024-08-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugalooAPI', '0015_financelog_trip_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertripinfo',
            name='places_descriptions',
            field=models.TextField(default=''),
        ),
    ]
